apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/trifanbogdan24/ci_cd_lab@sha256:c13594f2561bf6090d1048ddc3916df6d18e9b4d5206dd3e202626b59a8765d5
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

